---
- name: Retrieve architecture from Debian package manager
  ansible.builtin.command: dpkg --print-architecture
  register: architecture
    
- name: Retrieve distro specific information
  ansible.builtin.command: lsb_release -cs
  register: distro_info

- name: Install Docker Pre-Requisites
  ansible.builtin.apt:
    name: 
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: latest
    update_cache: yes 
    install_recommends: yes 
  become: yes

- name: Add Docker's official GPG Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
  become: yes

- name: Add Docker repository
  ansible.builtin.apt_repository:
    filename: /etc/apt/sources.list.d/docker.list
    repo: "deb [arch={{architecture.stdout_lines[0]}} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{distro_info.stdout_lines[0]}} stable"
    state: present
    update_cache: yes
  become: yes 

- name: Install Docker Engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: yes 
  become: yes

- name: Create docker group
  ansible.builtin.group:
    name: docker
    state: present
  become: yes

- name: Add user vagrant to group docker
  ansible.builtin.user:
    name: vagrant
    groups: docker
    append: yes 
  become: yes 

# running as ansible_local provisioner in vagrant, this does not work
# - name: reset ssh connection (this is for changes in docker group to take effect)
#   meta: reset_connection

# - name: Install docker python module
#   pip:
#     name: docker
#     executable: /usr/bin/python3
#   become: yes 