---
- name: configure host for MiniKube
  hosts: minikube
  vars:
    docker_prerequisite_packages:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    minikube_install_path: /usr/local/bin/minikube

  tasks:
    - name: Retrieve architecture from Debian package manager
      ansible.builtin.command: dpkg --print-architecture
      register: architecture
    
    - name: Retrieve distro specific information
      ansible.builtin.command: lsb_release -cs
      register: distro_info

    - name: Install Docker Pre-Requisites
      ansible.builtin.apt:
        name: "{{ docker_prerequisite_packages }}"
        state: latest
        update_cache: yes 
        install_recommends: yes 
      become: yes

    - name: Add Docker's official GPG Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /usr/share/keyrings/docker-archive-keyring.gpg
      become: yes 

    - name: Setup stable Docker repository
      ansible.builtin.copy:
        content: "deb [arch={{architecture.stdout_lines[0]}} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{distro_info.stdout_lines[0]}} stable"
        dest: /etc/apt/sources.list.d/docker.list
      become: yes 

    - name: Install Docker Engine
      ansible.builtin.apt:
        name: "{{docker_packages}}"
        update_cache: yes
        state: latest 
      become: yes 
    
    - name: Download MiniKube to install location
      ansible.builtin.get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: "{{minikube_install_path}}"
      become: yes 
    
    - name: Set MiniKube permissions
      ansible.builtin.file:
        path: "{{minikube_install_path}}"
        owner: vagrant
        group: vagrant
        mode: u=rwx,g=r-x,o=r-x
      become: yes

    - name: Set default MiniKube driver
      ansible.builtin.command: minikube config set driver docker
      
    - name: Create docker group
      ansible.builtin.group:
        name: docker
        state: present
      become: yes
    
    - name: Add user vagrant to group docker
      ansible.builtin.user:
        name: vagrant
        groups: docker
        append: yes 
      become: yes 

    # below isn't needed since when provisioner exits, it logs out user ansible, essentially accomplishing the same thing
    # - name: Activate changes to docker group
    #   ansible.builtin.command: newgrp docker